sudo: required
addons:
  chrome: stable
language: node_js
node_js:
  - "6.9"
  - "7"
  - "8"
branches:
  only:
  - master
before_install:
- cd packages/mip
install:
- npm install
script:
- npm run test:cover
after_success:
- cat ./coverage/lcov.info | coveralls